server:
  port: 8000

spring:
  application:
    name: "myTasks"
  datasource:
    url: jdbc:mysql://localhost:3306/mytasks
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


